# Generated by Django 4.2.1 on 2023-05-10 21:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_meeting_project_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
