# Generated by Django 4.2.1 on 2023-05-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default='Anywhere Street', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='Uganda', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='insitution',
            field=models.CharField(default='Institution', max_length=255),
            preserve_default=False,
        ),
    ]
