# Generated by Django 4.2.1 on 2023-05-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('partners', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='profile',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='user.profile'),
            preserve_default=False,
        ),
    ]
