# Generated by Django 4.2.1 on 2023-05-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_organization_address_organization_avatar_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.organization'),
        ),
    ]
